[package]
name = "rrpn"
version = "0.1.0"
authors = ["Jacob Alford"]
edition = "2021"

[dependencies]

dioxus = { version = "^0.5.1", features = ["web"] }

dioxus-logger = "^0.5.1"

wasm-bindgen = { version = "=0.2.92" }
