[application]

name = "rrpn"

default_platform = "web"

out_dir = "dist"

asset_dir = "assets"

[web.app]

title = "rrpn"

[web.watcher]

reload_html = true

watch_path = ["src", "assets"]

[web.resource]

style = []

script = []

[web.resource.dev]

script = []
